### PR TITLE
Add appveyor

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by marimeireles** [comment]
Cool! :D
Thanks Sylvain

**Comment by wolfv** [comment]
I think you should set the mamba root prefix to something as the home directory seems non-writable on Appveyor:

Calling shell init like this: `.\micromamba.exe shell init -s powershell -p C:\projects\rhumba\mamba_env` could do the trick.
After that, continue using powershell, and use `micromamba` instead of `mamba`. Also one needs to pass the channels all the time, so `-c conda-forge`.

**Comment by wolfv** [comment]
maybe `C:\projects\buildenv`?

**Comment by SylvainCorlay** [comment]
Since appveyor is already failing (before the PR), and this leads all the way to start the build with the right compiler, merging this as a net improvement.

**Pull request merged**
